baseURL = "https://silverjake.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Jake Silver"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = 'Jake Silver'

[params]

    greeting = "Thanks for visiting!"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:contact@silverjake.com"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/jakesilver"

    [[params.links]]
        icon = "linkedin"
        title = "Linkedin"
        url = "https://linkedin.com/in/jake-silver"

    [params.colors]
        background = "#b984a5"
        foreground = "#fff"
        hover = "#333"